version: '3.5'

networks:
  default:
    driver: bridge
# DATA
volumes:
    prometheus_data:
    prometheus_config:
    grafana_data:
    grafana_config:
    nginx_data:
    pg_data:

services:
# NGINX PROXY MANAGER
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager-app
    restart: unless-stopped
    ports:
      - '80:80'
     # - '43013:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm-usr1"
      DB_MYSQL_PASSWORD: "npm-pwd1"
      DB_MYSQL_NAME: "npm"
    volumes:
      - ./nginx_data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - default
    labels:
      org.label-schema.group: "monitoring"

# NGINX PROXY MANAGER DB
  db:
    image: 'jc21/mariadb-aria:latest'
    container_name: nginx-proxy-manager-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'npm-npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm-usr1'
      MYSQL_PASSWORD: 'npm-pwd1'
    volumes:
      - ./nginx_data/mysql:/var/lib/mysql
    networks:
      - default
    labels:
      org.label-schema.group: "monitoring"

# POSTGRES
  pg:
    container_name: pg-db
    image: postgres:13.9-alpine3.17
