apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: https://prometheus.emphasis.tk
    basicAuth: false
    isDefault: true
    editable: true